stages:
  - build
  - deploy

variables:
  #GLOBAL
  IMAGE_NAME: ssv-dkg
  DOCKER_BUILDKIT: 1

  #PRODUCTION
  ACCOUNT_ID_INFRA_PROD: 764289642555
  AWS_REGION_INFRA_PROD: "us-west-2"
  DOCKER_REPO_INFRA_PROD: $ACCOUNT_ID_INFRA_PROD.dkr.ecr.$AWS_REGION_INFRA_PROD.amazonaws.com/$IMAGE_NAME
  APP_REPLICAS_INFRA_PROD: "1"
  ECRLOGIN_INFRA_PROD: "aws ecr get-login --registry-ids $ACCOUNT_ID_INFRA_PROD --region $AWS_REGION_INFRA_PROD --no-include-email"
  PROD_HEALTH_CHECK_IMAGE: 764289642555.dkr.ecr.us-west-2.amazonaws.com/infra-prod-repo:ubuntu20


# +---------------+
# |     Prod      |
# +---------------+
Build prod Docker image:
  image: docker:20.10.23
  stage: build
  tags:
    - blox-infra-prod
  script:
    - apk add --no-cache py-pip
    - pip install pyyaml==5.3.1
    - pip install awscli
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA -f Dockerfile .
    - DOCKER_LOGIN_TO_INFRA_PROD_REPO=`$ECRLOGIN_INFRA_PROD`
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $DOCKER_REPO_INFRA_PROD:$CI_COMMIT_SHA
    - $DOCKER_LOGIN_TO_INFRA_PROD_REPO && docker push $DOCKER_REPO_INFRA_PROD:$CI_COMMIT_SHA

  only:
    - main

Deploy nodes to prod:
  stage: deploy
  tags:
    - blox-infra-prod
  script:
    - apk add bash curl
    - export K8S_API_VERSION=$INFRA_PROD_K8_API_VERSION
    - export SSV_DKG_CPU_LIMIT=$PROD_SSV_DKG_CPU_LIMIT
    - export SSV_DKG_MEM_LIMIT=$PROD_SSV_DKG_MEM_LIMIT
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/bin/kubectl
    - mkdir ~/.kube/
    - echo $PROD_KUBECONFIG | base64 -d > kubeconfig
    - mv kubeconfig ~/.kube/
    - export KUBECONFIG=~/.kube/kubeconfig
    - kubectl config get-contexts
    # +-------------------------------+
    # |      Deploy ssv-dkg nodes     |
    # +-------------------------------+
    - .k8/production/ssv-dkg/scripts/deploy-ssv-dkg-1--4.sh $DOCKER_REPO_INFRA_PROD $CI_COMMIT_SHA ssv $APP_REPLICAS_INFRA_PROD blox-infra-prod kubernetes-admin@blox-infra-prod ssv.network $K8S_API_VERSION $SSV_DKG_CPU_LIMIT $SSV_DKG_MEM_LIMIT
  only:
    - main
